name: UnitedSkills
version: '${project.version}'
main: org.unitedlands.skills.UnitedSkills
api-version: 1.21
depend:
  - Jobs
  - Towny
  - UltimateTimber
  - ItemsAdder
authors: [ Maroon28 ]
contributors: [ Litning11, Theriel_ ]
description: A plugin built to manage job skills for UnitedLands
website: unitedlands.org
commands:
  blend:
    description: Opens the blending GUI
    permission: united.skills.blendcommand
  unitedskills:
    description: Main command for the plugin, currently only reloads the plugin
    permission: united.skills.admin
  points:
    description: Main command for managing points
    permission: united.skills.admin